version: '3'


services:
  proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: registry.csc.sibsutis.ru/iv021s19/vtechlabs:lab4
    labels:
      - "traefik.http.routers.server.rule=Host(`localhost`)"
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`localhost`)&&Path(`/app`)"
